apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
        service: reverse-proxy
    spec:
      containers:
      - image: sherifgamil/reverseproxy:latest
        name: reverse-proxy
        #command: [ "sleep" ]
        #args: [ "infinity" ]
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always