version: "3"
services:
  reverseproxy:
    build:
        context: .
    image: sherifgamil/reverseproxy 
  backend_user:
    build:
        context: ../../udacity-c2-restapi-user
    image: sherifgamil/udacity-restapi-user
  backend_feed:
    build:
        context: ../../udacity-c2-restapi-feed  
    image: sherifgamil/udacity-restapi-feed
  frontend:
    build:
        context: ../../udacity-c2-frontend  
    image: sherifgamil/udacity-frontend