version: "3"
services:
  reverseproxy:
    build:
        context: .
    image: sherifgamil/reverseproxy:latest
  backend_user:
    build:
        context: ../../udacity-c2-restapi-user
    image: sherifgamil/udacity-restapi-user:latest
  backend_feed:
    build:
        context: ../../udacity-c2-restapi-feed  
    image: sherifgamil/udacity-restapi-feed:latest
  frontend:
    build:
        context: ../../udacity-c2-frontend  
    image: sherifgamil/udacity-frontend:latest